FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Create an empty tests directory
RUN mkdir -p tests

# Copy test_controller.py into tests directory
COPY tests/test_controller.py tests/

ENV SELENIUM_REMOTE_URL=http://selenium-hub:4444/wd/hub

# Run the tests and then keep the container running indefinitely
CMD pytest tests/ --maxfail=5 --disable-warnings -v && sleep infinity
