apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
    - name: port-4442
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: port-4443
      protocol: TCP
      port: 4443
      targetPort: 4443
    - name: port-4444
      protocol: TCP
      port: 4444
      targetPort: 4444